spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Solaris86/master-microservices-config.git
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#        native:
#          search-locations: "file:///Users//nikolasuscevic//Documents//Udemy//master-microservices-spring-boot-docker-kubernetes//config"
#          search-location: "classpath:/config"

server:
  port: 8071
